// <auto-generated />
namespace HobbyManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TestingModelBuilderFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestingModelBuilderFK));
        
        string IMigrationMetadata.Id
        {
            get { return "202106301839409_TestingModelBuilderFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
